# Use root/example as user/password credentials

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: bumdes_pangyangan
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - 3305:3306
    volumes:
      - ./docker/volumes/db:/var/lib/mysql
    # (this is just an example, not intended to be a production configuration)
